---
development:
  cloud_name: daa6g1ptr
  api_key: '486812474943738'
  api_secret: CdEnrYQXBtUNNEbkKOA0yeCT4gw
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: daa6g1ptr
  api_key: '486812474943738'
  api_secret: CdEnrYQXBtUNNEbkKOA0yeCT4gw
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: daa6g1ptr
  api_key: '486812474943738'
  api_secret: CdEnrYQXBtUNNEbkKOA0yeCT4gw
  enhance_image_tag: true
  static_file_support: false
